### ISSUE TITLE
Stored procedure call-out with Oracle custom types 

### ISSUE THREAD

**Issue by trevorrebelo** [jbrazda/com.informatica.cloud.das#1]
How do we pass or get parameters of custom type while calling a Oracle stored procedure ?

**Comment by jbrazda** [comment]
To invoke stored procedure or Oracle package function you have to use Following request example

```xml
<DataAccessRequest>
   <sqlStatement>
      <statementId>SOME_PKG.function</statementId>
      <columnCase>lowercase</columnCase>
      <hasResultSet>false</hasResultSet>
      <statement>CALL SOME_PKG.function(?,?)</statement>
      <procedure>
         <procedureParameter>
            <name>PARAMETER1</name>
            <sqlType>string</sqlType>
            <mode>in</mode> 
            <data>{$p1data}</data>
         </procedureParameter>
         <procedureParameter>
            <name>PARAMETER2</name>
            <sqlType>string</sqlType>
            <mode>in</mode>
            <data>{$p1data}</data>
         </procedureParameter>
      </procedure>
   </sqlStatement>  
   <dataSource>DS1</dataSource>
</DataAccessRequest>
```

Important part is to map the parameter types correctly with the respect of the SQL types
DAS does not support Oracle object array types, only following types are supported

Parameter attribute. Types include string (default), byte, short, int, long, float, double, date, binary, or clob
Binary  requires special handling to send data as attachment and it is not supported by this DAS wrapper implementation

You should be able to specify both in/out parameters - read more about data access service here

https://docs.informatica.com/process-automation/informatica-activevos/current-version/2----designer/building-a-process-with-a-system-service/data-access-service.html
